### PR TITLE
Translations updated

### PR DESCRIPTION
**Pull request by HansSchouten**
This pull request updates the translations of the Contact module. It also fixes an error in the permission configuration that prevented the role editor from loading.

### CODE REVIEW

**Comment by nWidart** [comment]
Thank you! 👍 
Tests seem to be failing: https://travis-ci.org/AsgardCms/Contact/jobs/292665622

**Comment by HansSchouten** [comment]
I replaced _config('mail.from.address')_ with _setting('contact::email')_ in SendContactRequestNotification.php, because I think it is better to use the email address the admin entered in the backend than to use a hardcoded email address. However, the setting method cannot be found. I can change that back, what is your opinion?

**Comment by nWidart** [comment]
Hm I see, why not yea.

To make tests pass you can't use the `setting` helper, or you need to require the helpers file. You might also need to create that setting.

**Comment by HansSchouten** [comment]
It is quite some work to add the helper, adding the dependency isn't enough. I now used a workaround by adding the environment variable to phpunit.xml. If I am correct this package is mostly used in combination with AsgardCms/Platform in which case the Settings module is always available and everything works perfect. In case it is used otherwise, they could add MAIL_TO_ADMIN to the .env file.

**Comment by nWidart** [comment]
Oh so you're not using the email from the settings anymore?

**Comment by HansSchouten** [comment]
Instead of _$email = env('MAIL_TO_ADMIN') ?: config('mail.from.address');_ it now uses _$email = env('MAIL_TO_ADMIN') ?: setting('contact::email');_. So instead of 2 hardcoded options, it still offers the pre configured option in the .env file. In case the environment variable is not set, it assumes the Settings module is available and it will use the email setting the admin provided in the backend. The test now passes because I added the environment variable to the phpunit.xml file.
I will use it myself in this way, but if it is not desirable I can change it back to the original line of code.

**Comment by nWidart** [comment]
Just tested and works great, thanks! 👍

**Comment by nWidart** [comment]
Hm translations are not loaded on travis, yet they are locally. 🤔

**Comment by nWidart** [comment]
Fixed and tagged as `3.1` 👍

**Pull request merged**
